import { DomController, NavController, NavParams, Ion, GestureController, Config, Platform, ToastController, Events } from 'ionic-angular';
import { AfterViewInit, ElementRef, NgZone, OnDestroy, OnInit, Renderer } from '@angular/core';
import { DomSanitizer, SafeUrl } from '@angular/platform-browser';
import { ImageViewerTransitionGesture } from './image-viewer-transition-gesture';
import { SocialSharing } from "@ionic-native/social-sharing";
import { ImageViewerOptions } from './image-viewer';
export declare class ImageViewerComponent extends Ion implements OnInit, OnDestroy, AfterViewInit {
    _gestureCtrl: GestureController;
    elementRef: ElementRef;
    private _nav;
    private _zone;
    private renderer;
    private domCtrl;
    private platform;
    private _navParams;
    private _socialShare;
    private _toastCtrl;
    private _events;
    private _sanitizer;
    imageUrl: SafeUrl;
    private imageUrlString;
    dragGesture: ImageViewerTransitionGesture;
    imageContainer: any;
    image: any;
    deletable: boolean;
    shareable: boolean;
    sendShareEvent: boolean;
    private pinchGesture;
    private options;
    isZoomed: boolean;
    private unregisterBackButton;
    constructor(_gestureCtrl: GestureController, elementRef: ElementRef, _nav: NavController, _zone: NgZone, renderer: Renderer, domCtrl: DomController, platform: Platform, _navParams: NavParams, _socialShare: SocialSharing, _toastCtrl: ToastController, _events: Events, _config: Config, _sanitizer: DomSanitizer);
    updateImageSrc(src: any): void;
    updateImageSrcWithTransition(src: any): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    bdClick(): void;
    openShareSheet(): void;
    sendEvent(eventName: string): void;
    setOptions(options?: ImageViewerOptions): void;
}
